### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by gedw99** [fermayo/shelly-bulk-update#1]
Presume this is for vision firmware ?

i need to do the same and this code does it nicely m.

I presume you feed it a GitHub release path ?

**Comment by fermayo** [comment]
Hey @gedw99,

This is for the official firmware. You don't need to pass anything to the command, as it just triggers the self-update on each device - if they find a newer version, they update, otherwise it does nothing.

I hope that helps!

**Comment by gedw99** [comment]
Makes sense . Thanks.

I am looking for a pure golang is on Shelly using tinygo. 

But this updater is still useful even for that
