### ISSUE TITLE
Does not work with Shelly Gen3 devices

### ISSUE THREAD

**Issue by speedyuy** [fermayo/shelly-bulk-update#12]
mDNS discovery in Wireshark shows a string "gen=3" with Gen 3 devices.
It defaults to Gen 1 when the string doesn't match.
The code is hardcoded with "gen=2" even if greater versions will probably use the same gen 2 protocol.
I guess the code could check for "gen=X" where X >= 2

**Comment by fermayo** [comment]
Thanks @speedyuy for reporting. I don't have a gen3 device - could you try the [version of this zip file](https://github.com/fermayo/shelly-bulk-update/actions/runs/12140511165/artifacts/2267396665) and see if it works for you? Thanks!

**Comment by speedyuy** [comment]
The changes worked great for Gen3 devices. I had already made one of those changes, sorry I don't know how to make the pull request.
Thanks for the fix @fermayo !
