### ISSUE TITLE
Support for Raspberry Pi

### ISSUE THREAD

**Issue by swingchampion** [fermayo/shelly-bulk-update#2]
I'm getting the following error on my Raspberry Pi when I try to run the `./shelly-bulk-update` command: `bash: ./shelly-bulk-update: cannot execute binary file: Exec format error`. 

I've downloaded the linux version with the following command: `curl -sSL https://github.com/fermayo/shelly-bulk-update/releases/download/v1.0/shelly-bulk-update-Linux-x86_64 -o shelly-bulk-update; chmod +x shelly-bulk-update`.

I'm not 100% sure if the files aren't supported on the Raspberry Pi or if I did something wrong. Thank you for the help.

**Comment by fermayo** [comment]
@swingchampion can you try to run this instead?

```
curl -sSL https://github.com/fermayo/shelly-bulk-update/releases/download/v1.0/shelly-bulk-update-Linux-armv7 -o shelly-bulk-update; chmod +x shelly-bulk-update
```

**Comment by swingchampion** [comment]
Works now. Thank you very much. How would I have to proceed if I want to execute the command automatically every day at 1am?

**Comment by fermayo** [comment]
You can use `crontab` for that: https://www.raspberrypi.org/documentation/computers/using_linux.html#scheduling-tasks-with-cron
