### ISSUE TITLE
Support for restricted access Shelly devices

### ISSUE THREAD

**Issue by ChirpyTurnip** [fermayo/shelly-bulk-update#3]
Hi,

When I run the bulk update tool (on Windows) I get the following message for each Shelly that is discovered:

Failed to query update status: invalid character 'U' after top-level value, aborting

I suspect this is because access to each Shelly is restricted with a password (to block tinkering visitors and teenagers). A GUI or CLI that allows the entry of credentials would be useful. 

Thanks!

CP.

**Comment by ChirpyTurnip** [comment]
Just saw this was on your to-do list already. ;-)

**Comment by fermayo** [comment]
@ChirpyTurnip just went ahead and implemented it. Check out [v1.1](https://github.com/fermayo/shelly-bulk-update/releases/tag/v1.1)!

**Comment by ChirpyTurnip** [comment]
Awesome! All my Shelly's are currently up to date (25 fine the hard way)
but I should get some new ones this week so that will give me a couple of
new ones to test on...  :-)

**Comment by ChirpyTurnip** [comment]
Hi,

I had a go at running the new version (from Windows Command Prompt) and
didn't have much success.....  here's my output:

C:\Users\bartt\Downloads>shelly-bulk-update-Windows-x86_64.exe --username
admin --password XXXXXXX
Using basic authentication: admin:*******
[scanner] looking for Shelly devices using mDNS (60s timeout)...
[shelly1pm-E8DB84A2037D.local.] checking for updates...
[shellydimmer2-3C6105E403ED.local.] checking for updates...
[shelly1pm-E8DB84A2037D] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...
[shellyswitch25-8CAAB561DF52.local.] checking for updates...
[shelly1-E8DB84D7B8CE.local.] checking for updates...
[shelly1pm-E8DB84D7E5AB.local.] checking for updates...
[shelly1-98CDAC249813.local.] checking for updates...
[shelly1-98CDAC249813] failed to check for updates: unexpected status code:
401, aborting...
[shellydimmer2-3C6105E403ED] failed to query update status: parse
"http://%s/ota":
invalid URL escape "%s", aborting...
[shelly1pm-3C6105E5C981.local.] checking for updates...
[shellydimmer2-3C6105E476C5.local.] checking for updates...
[shellyswitch25-8CAAB561DF52] failed to query update status: parse
"http://%s/ota":
invalid URL escape "%s", aborting...
[shellydimmer2-3C6105E40ECE.local.] checking for updates...
[shelly1pm-3C6105E57333.local.] checking for updates...
[shelly1-E8DB84D7B8CE] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...
[shelly1pm-E8DB84D7E5AB] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...
[shelly1pm-E8DB84D7D7E8.local.] checking for updates...
[shelly1pm-3C6105E5C981] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...
[shellydimmer2-3C6105E476C5] failed to query update status: parse
"http://%s/ota":
invalid URL escape "%s", aborting...
[shellyem3-E8DB84D6874F.local.] checking for updates...
[shellydimmer2-3C6105E40ECE] failed to query update status: parse
"http://%s/ota":
invalid URL escape "%s", aborting...
[shelly1pm-3C6105E57333] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...
[shelly1pm-E8DB84D7D7E8] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...
[shellydimmer2-3C6105E40DD3.local.] checking for updates...
[shellyem3-E8DB84D6874F] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...
[shelly1pm-E8DB84D4924E.local.] checking for updates...
[shellydimmer2-3C6105E31FA6.local.] checking for updates...
[shelly1pm-E8DB84D7D773.local.] checking for updates...
[shellydimmer2-3C6105E40DD3] failed to query update status: parse
"http://%s/ota":
invalid URL escape "%s", aborting...
[shelly1pm-E8DB84A26F15.local.] checking for updates...
[shelly1-98CDAC253BBF.local.] checking for updates...
[shellydimmer2-3C6105E3E5FB.local.] checking for updates...
[shellyswitch25-8CAAB561DFF2.local.] checking for updates...
[shellydimmer2-3C6105E3953D.local.] checking for updates...
[shellydimmer2-3C6105E32D59.local.] checking for updates...
[shelly1pm-E8DB84D4924E] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...
[shellydimmer2-3C6105E3D888.local.] checking for updates...
[shelly1pm-3C6105E5A7A0.local.] checking for updates...
[shellydimmer2-3C6105E31FA6] failed to query update status: parse
"http://%s/ota":
invalid URL escape "%s", aborting...
[shelly1pm-E8DB84D7D773] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...
[shelly1pm-3C6105E5679B.local.] checking for updates...
[shelly1pm-E8DB84A26F15] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...
[shelly1-98CDAC253BBF] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...
[shellydimmer2-3C6105E3E5FB] failed to query update status: parse
"http://%s/ota":
invalid URL escape "%s", aborting...
[shellyswitch25-8CAAB561DFF2] failed to query update status: parse
"http://%s/ota":
invalid URL escape "%s", aborting...
[shellydimmer2-3C6105E3953D] failed to query update status: parse
"http://%s/ota":
invalid URL escape "%s", aborting...
[shellydimmer2-3C6105E32D59] failed to query update status: parse
"http://%s/ota":
invalid URL escape "%s", aborting...
[shellydimmer2-3C6105E3D888] failed to query update status: parse
"http://%s/ota":
invalid URL escape "%s", aborting...
[shelly1pm-3C6105E5A7A0] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...
[shelly1pm-3C6105E5679B] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...
[shelly1pm-E8DB84A27381.local.] checking for updates...
[shelly1pm-E8DB84A27381] failed to query update status: parse "http://%s/ota":
invalid URL escape "%s", aborting...

Then I looked for my new ones (no local access password set yet) and I got
the same error messages.....

Am I missing something obvious?

CP.

**Comment by fermayo** [comment]
@ChirpyTurnip oops, I introduced a bug in the latest version, my bad! Please try out v1.2: https://github.com/fermayo/shelly-bulk-update/releases/tag/v1.2

**Comment by ChirpyTurnip** [comment]
Hi,

With the recent release of new firmware I was finally able to try v1.2
again. Here are my results:

C:\User Data>shelly-bulk-update-Windows-x86_64.exe --username admin
--password XXXXXXX
Using basic authentication: admin:*******
[scanner] looking for Shelly devices using mDNS (60s timeout)...
[shelly1pm-E8DB84A26F15.local.] checking for updates...
[shelly1-C45BBE5F2F1D.local.] checking for updates...
[shelly1pm-E8DB84A27381.local.] checking for updates...
[shellydimmer2-3C6105E40ECE.local.] checking for updates...
[shelly1-98CDAC249813.local.] checking for updates...
[shelly1-98CDAC249813] failed to check for updates: unexpected status code:
401, aborting...
[shelly1pm-E8DB84D7D7E8.local.] checking for updates...
[shelly1-E8DB84D7B8CE.local.] checking for updates...
[shelly1pm-98CDAC1ED7C2.local.] checking for updates...
[shellydimmer2-3C6105E3953D.local.] checking for updates...
[shelly1pm-E8DB84A26F15.local.] update available!
(20210909-145919/v1.11.4-DNSfix-ge6b2f6d ->
20211109-130756/v1.11.7-g682a0db), updating...
[shelly1-C45BBE5F2F1D.local.] update available!
(20210909-144114/v1.11.4-DNSfix-ge6b2f6d ->
20211109-124958/v1.11.7-g682a0db), updating...
[shelly1pm-E8DB84A27381.local.] update available!
(20210909-145919/v1.11.4-DNSfix-ge6b2f6d ->
20211109-130756/v1.11.7-g682a0db), updating...
[shellydimmer2-3C6105E476C5.local.] checking for updates...
[shellydimmer2-3C6105E40ECE.local.] update available!
(20210909-150154/v1.11.4-DNSfix-ge6b2f6d ->
20211109-131033/v1.11.7-g682a0db), updating...
[shelly1pm-E8DB84D7E5AB.local.] checking for updates...
[shelly1pm-E8DB84D7D7E8.local.] update available!
(20210909-145919/v1.11.4-DNSfix-ge6b2f6d ->
20211109-130756/v1.11.7-g682a0db), updating...
[shelly1-E8DB84D7B8CE.local.] update available!
(20210909-144114/v1.11.4-DNSfix-ge6b2f6d ->
20211109-124958/v1.11.7-g682a0db), updating...
[shelly1pm-98CDAC1ED7C2.local.] update available!
(20210909-145919/v1.11.4-DNSfix-ge6b2f6d ->
20211109-130756/v1.11.7-g682a0db), updating...
[shelly1pm-E8DB84A2037D.local.] checking for updates...
[shellydimmer2-3C6105E403ED.local.] checking for updates...
[shellydimmer2-3C6105E3953D.local.] update available!
(20210909-150154/v1.11.4-DNSfix-ge6b2f6d ->
20211109-131033/v1.11.7-g682a0db), updating...
[shelly1pm-98CDAC1F349E.local.] checking for updates...
[shellydimmer2-3C6105E3E5FB.local.] checking for updates...
[shelly1pm-E8DB84D7E5AB.local.] update available!
(20210909-145919/v1.11.4-DNSfix-ge6b2f6d ->
20211109-130756/v1.11.7-g682a0db), updating...
[shellydimmer2-3C6105E476C5.local.] update available!
(20210909-150154/v1.11.4-DNSfix-ge6b2f6d ->
20211109-131033/v1.11.7-g682a0db), updating...
[shelly1pm-3C6105E5679B.local.] checking for updates...
[shelly1pm-E8DB84A2037D.local.] update available!
(20210909-145919/v1.11.4-DNSfix-ge6b2f6d ->
20211109-130756/v1.11.7-g682a0db), updating...
[shellydimmer2-3C6105E403ED.local.] update available!
(20210909-150154/v1.11.4-DNSfix-ge6b2f6d ->
20211109-131033/v1.11.7-g682a0db), updating...
[shelly1-98CDAC253BBF.local.] checking for updates...
[shellyswitch25-8CAAB561DFF2.local.] checking for updates...
[shellyem3-E8DB84D6874F.local.] checking for updates...
[shelly1pm-3C6105E5679B.local.] update available!
(20210909-145919/v1.11.4-DNSfix-ge6b2f6d ->
20211109-130756/v1.11.7-g682a0db), updating...
[shelly1pm-3C6105E5C981.local.] checking for updates...
[shellydimmer2-3C6105E3E5FB.local.] update available!
(20210909-150154/v1.11.4-DNSfix-ge6b2f6d ->
20211109-131033/v1.11.7-g682a0db), updating...
[shelly1pm-3C6105E5A7A0.local.] checking for updates...
[shelly1pm-E8DB84D4924E.local.] checking for updates...
[shellydimmer2-3C6105E3D888.local.] checking for updates...
[shellydimmer2-3C6105E31FA6.local.] checking for updates...
[shelly1-98CDAC253BBF.local.] update available!
(20210909-144114/v1.11.4-DNSfix-ge6b2f6d ->
20211109-124958/v1.11.7-g682a0db), updating...
[shellyem3-E8DB84D6874F.local.] update available!
(20210909-150410/v1.11.4-DNSfix-ge6b2f6d ->
20211109-131251/v1.11.7-g682a0db), updating...
[shellyswitch25-8CAAB561DF52.local.] checking for updates...
[shelly1pm-3C6105E57333.local.] checking for updates...
[shellydimmer2-3C6105E40DD3.local.] checking for updates...
[shelly1pm-3C6105E5C981.local.] update available!
(20210909-145919/v1.11.4-DNSfix-ge6b2f6d ->
20211109-130756/v1.11.7-g682a0db), updating...
[shellydimmer2-3C6105E32D59.local.] checking for updates...
[shelly1pm-3C6105E5A7A0.local.] update available!
(20210909-145919/v1.11.4-DNSfix-ge6b2f6d ->
20211109-130756/v1.11.7-g682a0db), updating...
[shelly1pm-E8DB84D4924E.local.] update available!
(20210909-145919/v1.11.4-DNSfix-ge6b2f6d ->
20211109-130756/v1.11.7-g682a0db), updating...
[shellydimmer2-3C6105E3D888.local.] update available!
(20210909-150154/v1.11.4-DNSfix-ge6b2f6d ->
20211109-131033/v1.11.7-g682a0db), updating...
[shellydimmer2-3C6105E31FA6.local.] update available!
(20210909-150154/v1.11.4-DNSfix-ge6b2f6d ->
20211109-131033/v1.11.7-g682a0db), updating...
[shellydimmer2-3C6105E3953D] failed to query update status: Get "
http://192.168.20.111/ota": dial tcp 192.168.20.111:80: i/o timeout,
retrying...
[shelly1pm-98CDAC1F349E] failed to query update status: Get "
http://192.168.20.127/ota": dial tcp 192.168.20.127:80: i/o timeout,
aborting...
[shelly1pm-E8DB84A27381] failed to query update status: Get "
http://192.168.20.103/ota": dial tcp 192.168.20.103:80: i/o timeout,
retrying...
[shelly1pm-3C6105E57333.local.] update available!
(20210909-145919/v1.11.4-DNSfix-ge6b2f6d ->
20211109-130756/v1.11.7-g682a0db), updating...
[shellydimmer2-3C6105E40DD3.local.] update available!
(20210909-150154/v1.11.4-DNSfix-ge6b2f6d ->
20211109-131033/v1.11.7-g682a0db), updating...
[shellydimmer2-3C6105E32D59.local.] update available!
(20210909-150154/v1.11.4-DNSfix-ge6b2f6d ->
20211109-131033/v1.11.7-g682a0db), updating...
[shellyswitch25-8CAAB561DF52.local.] update available!
(20210909-144331/v1.11.4-DNSfix-ge6b2f6d ->
20211109-125214/v1.11.7-g682a0db), updating...
[shellyswitch25-8CAAB561DFF2] failed to query update status: Get "
http://192.168.20.108/ota": dial tcp 192.168.20.108:80: i/o timeout,
aborting...
[scanner] scanning process finished
[shelly1pm-E8DB84A2037D] failed to query update status: Get "
http://192.168.20.118/ota": dial tcp 192.168.20.118:80: i/o timeout,
retrying...
[shelly1pm-E8DB84A26F15] failed to query update status: Get "
http://192.168.20.101/ota": dial tcp 192.168.20.101:80: i/o timeout,
retrying...
[shelly1pm-E8DB84D7E5AB] failed to query update status: Get "
http://192.168.20.100/ota": dial tcp 192.168.20.100:80: i/o timeout,
retrying...
[shellydimmer2-3C6105E3953D] device updated to
20211109-131033/v1.11.7-g682a0db!
[shelly1pm-E8DB84A26F15] device updated to 20211109-130756/v1.11.7-g682a0db!
[shelly1pm-E8DB84D7E5AB] device updated to 20211109-130756/v1.11.7-g682a0db!
[shellydimmer2-3C6105E40ECE] device updated to
20210909-150154/v1.11.4-DNSfix-ge6b2f6d!
[shellydimmer2-3C6105E476C5] device updated to
20211109-131033/v1.11.7-g682a0db!
[shellydimmer2-3C6105E3D888] device updated to
20211109-131033/v1.11.7-g682a0db!
[shelly1pm-E8DB84A27381] failed to query update status: Get "
http://192.168.20.103/ota": dial tcp 192.168.20.103:80: i/o timeout,
retrying...
[shelly1pm-E8DB84A27381] device updated to 20211109-130756/v1.11.7-g682a0db!
[shelly1pm-E8DB84D7D7E8] failed to query update status: Get "
http://192.168.20.102/ota": dial tcp 192.168.20.102:80: i/o timeout,
retrying...
[shelly1pm-98CDAC1ED7C2] failed to query update status: Get "
http://192.168.20.126/ota": dial tcp 192.168.20.126:80: i/o timeout,
retrying...
[shellydimmer2-3C6105E403ED] failed to query update status: Get "
http://192.168.20.104/ota": dial tcp 192.168.20.104:80: i/o timeout,
retrying...
[shelly1pm-E8DB84A2037D] failed to query update status: Get "
http://192.168.20.118/ota": dial tcp 192.168.20.118:80: i/o timeout,
retrying...
[shellydimmer2-3C6105E32D59] device updated to
20210909-150154/v1.11.4-DNSfix-ge6b2f6d!
[shelly1pm-E8DB84D7D7E8] device updated to 20211109-130756/v1.11.7-g682a0db!
[shelly1pm-98CDAC1ED7C2] device updated to 20211109-130756/v1.11.7-g682a0db!
[shelly1pm-E8DB84A2037D] device updated to 20211109-130756/v1.11.7-g682a0db!
[shellydimmer2-3C6105E403ED] device updated to
20211109-131033/v1.11.7-g682a0db!
[shelly1pm-3C6105E57333] failed to query update status: Get "
http://192.168.20.107/ota": dial tcp 192.168.20.107:80: i/o timeout,
retrying...
[shelly1pm-3C6105E57333] device updated to 20211109-130756/v1.11.7-g682a0db!
[shellydimmer2-3C6105E40DD3] failed to query update status: Get "
http://192.168.20.105/ota": dial tcp 192.168.20.105:80: i/o timeout,
retrying...
[shelly1pm-3C6105E5679B] failed to query update status: Get "
http://192.168.20.120/ota": dial tcp 192.168.20.120:80: i/o timeout,
retrying...
[shellydimmer2-3C6105E40DD3] device updated to
20211109-131033/v1.11.7-g682a0db!
[shelly1pm-3C6105E5679B] device updated to 20211109-130756/v1.11.7-g682a0db!
[shelly1-98CDAC253BBF] failed to query update status: Get "
http://192.168.20.113/ota": dial tcp 192.168.20.113:80: i/o timeout,
retrying...
[shelly1pm-3C6105E5A7A0] failed to query update status: Get "
http://192.168.20.124/ota": dial tcp 192.168.20.124:80: i/o timeout,
retrying...
[shelly1-98CDAC253BBF] device updated to 20211109-124958/v1.11.7-g682a0db!
[shelly1pm-3C6105E5A7A0] device updated to 20211109-130756/v1.11.7-g682a0db!
[shelly1pm-E8DB84D4924E] failed to query update status: Get "
http://192.168.20.123/ota": dial tcp 192.168.20.123:80: i/o timeout,
retrying...
[shelly1pm-3C6105E5C981] failed to query update status: Get "
http://192.168.20.121/ota": dial tcp 192.168.20.121:80: i/o timeout,
retrying...
[shellydimmer2-3C6105E31FA6] failed to query update status: Get "
http://192.168.20.117/ota": dial tcp 192.168.20.117:80: i/o timeout,
retrying...
[shelly1pm-3C6105E5C981] device updated to 20211109-130756/v1.11.7-g682a0db!
[shellydimmer2-3C6105E31FA6] device updated to
20211109-131033/v1.11.7-g682a0db!
[shelly1pm-E8DB84D4924E] device updated to 20211109-130756/v1.11.7-g682a0db!
[shellyswitch25-8CAAB561DF52] failed to query update status: Get "
http://192.168.20.109/ota": dial tcp 192.168.20.109:80: i/o timeout,
retrying...
[shellyswitch25-8CAAB561DF52] device updated to
20211109-125214/v1.11.7-g682a0db!
^C

At this point it had hung for about 10 minutes....so I did a CTRL+C to
break out. Not sure why it hung....would also suggest, if possible, putting
a timestamp at the start of each line to make it easier to tell if the
application is still running or or has stopped (and for how long). One of
the Shelly devices (a Shelly 1) would not be picked up here as it has a
different password (by design).

I restarted the process:

C:\User Data>
C:\User Data>shelly-bulk-update-Windows-x86_64.exe --username admin
--password XXXXXXX
Using basic authentication: admin:*******
[scanner] looking for Shelly devices using mDNS (60s timeout)...
[shellydimmer2-3C6105E40ECE.local.] checking for updates...
[shellydimmer2-3C6105E3D888.local.] checking for updates...
[shelly1pm-E8DB84A26F15.local.] checking for updates...
[shellydimmer2-3C6105E40DD3.local.] checking for updates...
[shellydimmer2-3C6105E40ECE] already up to date
(20211109-131033/v1.11.7-g682a0db)
[shellydimmer2-3C6105E3D888] already up to date
(20211109-131033/v1.11.7-g682a0db)
[shelly1pm-E8DB84A26F15] already up to date
(20211109-130756/v1.11.7-g682a0db)
[shelly1pm-98CDAC1F349E.local.] checking for updates...
[shellydimmer2-3C6105E40DD3] already up to date
(20211109-131033/v1.11.7-g682a0db)
[shellydimmer2-3C6105E32D59.local.] checking for updates...
[shelly1pm-3C6105E5C981.local.] checking for updates...
[shellydimmer2-3C6105E476C5.local.] checking for updates...
[shellydimmer2-3C6105E3953D.local.] checking for updates...
[shelly1pm-E8DB84A2037D.local.] checking for updates...
[shelly1pm-98CDAC1F349E.local.] update available!
(20210909-145919/v1.11.4-DNSfix-ge6b2f6d ->
20211109-130756/v1.11.7-g682a0db), updating...
[shelly1pm-3C6105E57333.local.] checking for updates...
[shelly1pm-E8DB84D4924E.local.] checking for updates...
[shellydimmer2-3C6105E32D59] already up to date
(20211109-131033/v1.11.7-g682a0db)
[shelly1pm-3C6105E5C981] already up to date
(20211109-130756/v1.11.7-g682a0db)
[shellydimmer2-3C6105E476C5] already up to date
(20211109-131033/v1.11.7-g682a0db)
[shelly1pm-3C6105E5679B.local.] checking for updates...
[shellyem3-E8DB84D6874F.local.] checking for updates...
[shelly1-98CDAC253BBF.local.] checking for updates...
[shellyswitch25-8CAAB561DF52.local.] checking for updates...
[shellyswitch25-8CAAB561DFF2.local.] checking for updates...
[shellydimmer2-3C6105E31FA6.local.] checking for updates...
[shelly1pm-E8DB84A27381.local.] checking for updates...
[shelly1-E8DB84D7B8CE.local.] checking for updates...
[shellydimmer2-3C6105E3E5FB.local.] checking for updates...
[shellydimmer2-3C6105E3953D] already up to date
(20211109-131033/v1.11.7-g682a0db)
[shelly1pm-E8DB84A2037D] already up to date
(20211109-130756/v1.11.7-g682a0db)
[shelly1pm-E8DB84D7D773.local.] checking for updates...
[shelly1pm-E8DB84D7E5AB.local.] checking for updates...
[shelly1pm-98CDAC1ED7C2.local.] checking for updates...
[shellydimmer2-3C6105E403ED.local.] checking for updates...
[shelly1pm-E8DB84D7D7E8.local.] checking for updates...
[shelly1pm-3C6105E5A7A0.local.] checking for updates...
[shelly1pm-3C6105E57333] already up to date
(20211109-130756/v1.11.7-g682a0db)
[shelly1pm-E8DB84D4924E] already up to date
(20211109-130756/v1.11.7-g682a0db)
[shelly1-98CDAC249813.local.] checking for updates...
[shelly1-98CDAC249813] failed to check for updates: unexpected status code:
401, aborting...
[shelly1pm-3C6105E5679B] already up to date
(20211109-130756/v1.11.7-g682a0db)
[shellyem3-E8DB84D6874F] already up to date
(20211109-131251/v1.11.7-g682a0db)
[shelly1-98CDAC253BBF] already up to date (20211109-124958/v1.11.7-g682a0db)
[shelly1pm-E8DB84A27381] already up to date
(20211109-130756/v1.11.7-g682a0db)
[shellydimmer2-3C6105E31FA6] already up to date
(20211109-131033/v1.11.7-g682a0db)
[shelly1-E8DB84D7B8CE] already up to date (20211109-124958/v1.11.7-g682a0db)
[shellydimmer2-3C6105E3E5FB] already up to date
(20211109-131033/v1.11.7-g682a0db)
[shellyswitch25-8CAAB561DFF2.local.] update available!
(20210909-144331/v1.11.4-DNSfix-ge6b2f6d ->
20211109-125214/v1.11.7-g682a0db), updating...
[shellyswitch25-8CAAB561DF52] already up to date
(20211109-125214/v1.11.7-g682a0db)
[shelly1pm-E8DB84D7D773.local.] update available!
(20210909-145919/v1.11.4-DNSfix-ge6b2f6d ->
20211109-130756/v1.11.7-g682a0db), updating...
[shelly1pm-E8DB84D7E5AB] already up to date
(20211109-130756/v1.11.7-g682a0db)
[shelly1pm-E8DB84D7D7E8] already up to date
(20211109-130756/v1.11.7-g682a0db)
[shelly1pm-98CDAC1ED7C2] already up to date
(20211109-130756/v1.11.7-g682a0db)
[shelly1pm-3C6105E5A7A0] already up to date
(20211109-130756/v1.11.7-g682a0db)
[shellydimmer2-3C6105E403ED] already up to date
(20211109-131033/v1.11.7-g682a0db)
[shelly1-C45BBE5F2F1D.local.] checking for updates...
[shelly1-C45BBE5F2F1D] already up to date (20211109-124958/v1.11.7-g682a0db)
[scanner] scanning process finished
[shellyswitch25-8CAAB561DFF2] failed to query update status: Get "
http://192.168.20.108/ota": dial tcp 192.168.20.108:80: i/o timeout,
retrying...
[shellyswitch25-8CAAB561DFF2] device updated to
20211109-125214/v1.11.7-g682a0db!
[shelly1pm-98CDAC1F349E] failed to query update status: Get "
http://192.168.20.127/ota": dial tcp 192.168.20.127:80: i/o timeout,
retrying...
[shelly1pm-E8DB84D7D773] failed to query update status: Get "
http://192.168.20.106/ota": dial tcp 192.168.20.106:80: i/o timeout,
retrying...
[shelly1pm-98CDAC1F349E] device updated to 20211109-130756/v1.11.7-g682a0db!
[shelly1pm-E8DB84D7D773] device updated to 20211109-130756/v1.11.7-g682a0db!

C:\User Data>

And then it exited. After manually updating the odd Shelly 1 Home Assistant
now reports that there are no devices in need of updating....so pretty
successful I think!

Kind regards,
Bart.
